export const customersContent = {
  sidebar: {
    status: "2,418 customers synced",
    detailStatus: "Customer profile open",
    promissoryStatus: "Promissória em análise",
    operatorRole: "Customer desk",
  },
  header: {
    title: "Customers",
    description: "Track loyalty, purchase history, birthdays, returns, and high-intent outreach.",
    searchPlaceholder: "Search name, phone, CPF",
    campaignLabel: "Campaign",
    actionLabel: "Add customer",
  },
  metrics: [
    ["Active customers", "1,284", "Bought in last 90 days", "info"],
    ["Loyalty members", "842", "R$ 38.2k points balance", "success"],
    ["Birthdays this week", "19", "7 high-value contacts", "warning"],
    ["Repeat rate", "41%", "+5 pts vs last month", "muted"],
  ],
  filters: [
    ["all", "All customers"],
    ["vip", "VIP"],
    ["birthday", "Birthday"],
    ["at-risk", "At risk"],
    ["returns", "Returns"],
    ["whatsapp", "WhatsApp opt-in"],
  ],
  table: {
    title: "Customer list",
    description: "Prioritize buyers by lifetime value, loyalty status, and next best action.",
    segmentLabel: "Segment",
    rows: [
      ["Marina Costa", "85 99142-7712", "Today", "R$ 4.8k", "VIP", "Reserve dress"],
      ["Beatriz Lima", "85 98801-3370", "2 days", "R$ 2.1k", "Loyalty", "Send lookbook"],
      ["Camila Rocha", "85 99718-1102", "8 days", "R$ 980", "Birthday", "Gift coupon"],
      ["Juliana Alves", "85 98944-2210", "16 days", "R$ 1.6k", "At risk", "WhatsApp"],
      ["Rafaela Nunes", "85 99200-8139", "21 days", "R$ 760", "Returns", "Fit note"],
      ["Larissa Melo", "85 98763-9042", "31 days", "R$ 3.4k", "VIP", "New arrival"],
      ["Fernanda Dias", "85 99620-4551", "45 days", "R$ 540", "Inactive", "Winback"],
      ["Patricia Souza", "85 99418-7006", "58 days", "R$ 1.1k", "Loyalty", "Points alert"],
    ],
  },
  bulkActions: {
    selected: "0 selected",
    hint: "Select customers to send messages, assign tags, or export a segment.",
  },
  rail: {
    initials: "MC",
    name: "Marina Costa",
    description: "VIP • WhatsApp opt-in",
    stats: [
      ["Lifetime", "R$ 4.8k"],
      ["Orders", "23"],
      ["Avg ticket", "R$ 209"],
    ],
    loyalty:
      "R$ 182 in points available. Next tier unlocks after R$ 420 in purchases.",
    actions: ["Reserve black midi dress", "Send birthday coupon", "Follow up on alteration"],
    purchases: [
      ["Vestido midi canelado", "Today • R$ 219"],
      ["Sandália tiras nude", "May 18 • R$ 189"],
      ["Calça alfaiataria", "May 02 • R$ 249"],
    ],
  },
  detail: {
    breadcrumb: "Customers / Mariana Costa",
    name: "Mariana Costa",
    description: "VIP customer • Last purchase 2 days ago • WhatsApp opt-in",
    email: "mariana.costa@email.com • +55 85 98842-7810",
    actions: ["Message", "Edit profile", "New order"],
    tags: ["VIP", "WhatsApp", "No debt"],
    stats: [
      ["Total spent", "R$ 8.420"],
      ["Orders", "37"],
      ["Avg. ticket", "R$ 227"],
      ["Loyalty points", "3.240"],
    ],
    tabs: ["Overview", "Orders", "Notes", "Preferences"],
    recentOrders: [
      ["#1048", "2 days ago", "R$ 420", "Paid"],
      ["#1032", "12 days ago", "R$ 189", "Picked up"],
      ["#1017", "Apr 30", "R$ 760", "Returned item"],
      ["#0991", "Apr 18", "R$ 238", "Paid"],
    ],
    notes: [
      "Prefers linen dresses in neutral colors.",
      "Usually buys near payday and responds on WhatsApp.",
      "Birthday: August 18. Offer early VIP preview.",
    ],
    loyaltyTier: {
      title: "Gold member",
      description: "R$ 580 until Platinum tier",
    },
    nextActions: ["Send birthday preview", "Offer linen dress restock", "Invite to VIP sale"],
    timeline: [
      ["Bought linen set", "2 days ago"],
      ["Redeemed loyalty credit", "12 days ago"],
      ["Opened WhatsApp campaign", "18 days ago"],
      ["Returned blouse for size change", "Apr 30"],
    ],
  },
  promissory: {
    breadcrumb: "Customers / Mariana Costa / Promissória",
    title: "Promissória de Mariana Costa",
    description:
      "Acompanhe parcelas, atrasos, pagamentos recentes, acordos e histórico de compras a prazo.",
    actions: ["Registrar pagamento", "Renegociar", "Exportar"],
    alertTitle: "Pagamento em atraso há 12 dias",
    alertDescription:
      "A parcela vencida em 14 de maio de 2026 ainda não foi baixada. Próxima ação recomendada: contato por WhatsApp hoje.",
    metrics: [
      ["Valor em aberto", "R$ 1.248,00", "3 parcelas pendentes"],
      ["Em atraso", "R$ 416,00", "12 dias vencidos"],
      ["Último pagamento", "02 maio 2026", "R$ 416 via Pix"],
      ["Limite a prazo", "R$ 2.000,00", "62% utilizado"],
    ],
    installments: [
      ["14 maio 2026", "Vence em 12 dias", "R$ 416,00", "Atrasada"],
      ["14 junho 2026", "Vence em 19 dias", "R$ 416,00", "Em aberto"],
      ["14 julho 2026", "Vence em 49 dias", "R$ 416,00", "Em aberto"],
    ],
    purchases: [
      ["#1048 • Vestido linho + sandália", "02 maio 2026", "R$ 1.248,00"],
      ["#0991 • Blusa alfaiataria", "18 abr 2026", "R$ 238,00"],
    ],
    timeline: [
      ["Pagamento recebido", "02 maio • R$ 416 via Pix"],
      ["Compra parcelada criada", "02 maio • 3x de R$ 416"],
      ["Lembrete enviado", "15 maio • WhatsApp entregue"],
      ["Parcela atrasada", "26 maio • 12 dias vencidos"],
    ],
    risk: {
      label: "Risco de cobrança",
      value: "Médio",
      description: "Cliente historicamente paga após o primeiro lembrete.",
    },
  },
} as const;

export const customersContentByLocale = {
  en: {
    ...customersContent,
    labels: {
      loyaltyStatus: "Loyalty status",
      nextBestActions: "Next best actions",
      recentPurchases: "Recent purchases",
      recentOrders: "Recent orders",
      relationshipNotes: "Relationship notes",
      viewAll: "View all",
      loyaltyTier: "Loyalty tier",
      timeline: "Timeline",
      promissory: "Promissory",
    },
    promissory: {
      ...customersContent.promissory,
      breadcrumb: "Customers / Mariana Costa / Promissory",
      title: "Mariana Costa promissory",
      description:
        "Track installments, delays, recent payments, agreements and credit purchase history.",
      actions: ["Register payment", "Renegotiate", "Export"],
      alertTitle: "Payment overdue for 12 days",
      alertDescription:
        "The installment due on May 14, 2026 has not been settled. Recommended next action: WhatsApp contact today.",
      metrics: [
        ["Open amount", "R$ 1,248.00", "3 pending installments"],
        ["Overdue", "R$ 416.00", "12 days late"],
        ["Last payment", "May 02, 2026", "R$ 416 via Pix"],
        ["Credit limit", "R$ 2,000.00", "62% used"],
      ],
      installments: [
        ["May 14, 2026", "12 days overdue", "R$ 416.00", "Overdue"],
        ["June 14, 2026", "Due in 19 days", "R$ 416.00", "Open"],
        ["July 14, 2026", "Due in 49 days", "R$ 416.00", "Open"],
      ],
      purchases: [
        ["#1048 - Linen dress + sandal", "May 02, 2026", "R$ 1,248.00"],
        ["#0991 - Tailored blouse", "Apr 18, 2026", "R$ 238.00"],
      ],
      timeline: [
        ["Payment received", "May 02 - R$ 416 via Pix"],
        ["Installment purchase created", "May 02 - 3x R$ 416"],
        ["Reminder sent", "May 15 - WhatsApp delivered"],
        ["Installment overdue", "May 26 - 12 days late"],
      ],
      risk: {
        label: "Collection risk",
        value: "Medium",
        description: "Customer historically pays after the first reminder.",
      },
      labels: {
        creditPurchaseHistory: "Credit purchase history",
        financialTimeline: "Financial timeline",
        openInstallments: "Open installments",
        pendingInstallments: "3 pending",
      },
    },
  },
  "pt-BR": {
    ...customersContent,
    sidebar: {
      status: "2.418 clientes sincronizados",
      detailStatus: "Perfil de cliente aberto",
      promissoryStatus: "Promissoria em analise",
      operatorRole: "Mesa de clientes",
    },
    header: {
      title: "Clientes",
      description: "Acompanhe fidelidade, historico, aniversarios, devolucoes e contatos.",
      searchPlaceholder: "Buscar nome, telefone, CPF",
      campaignLabel: "Campanha",
      actionLabel: "Adicionar cliente",
    },
    metrics: [
      ["Clientes ativos", "1.284", "Compraram nos ultimos 90 dias", "info"],
      ["Membros fidelidade", "842", "R$ 38,2 mil em pontos", "success"],
      ["Aniversarios da semana", "19", "7 contatos de alto valor", "warning"],
      ["Taxa de recompra", "41%", "+5 pts vs mes passado", "muted"],
    ],
    filters: [
      ["all", "Todos"],
      ["vip", "VIP"],
      ["birthday", "Aniversario"],
      ["at-risk", "Em risco"],
      ["returns", "Devolucoes"],
      ["whatsapp", "WhatsApp opt-in"],
    ],
    table: {
      ...customersContent.table,
      title: "Lista de clientes",
      description: "Priorize compradores por valor vitalicio, fidelidade e proxima acao.",
      segmentLabel: "Segmento",
      heads: ["Cliente", "Telefone", "Ultima compra", "Vitalicio", "Segmento", "Proxima acao"],
      rows: [
        ["Marina Costa", "85 99142-7712", "Hoje", "R$ 4,8 mil", "VIP", "Reservar vestido"],
        ["Beatriz Lima", "85 98801-3370", "2 dias", "R$ 2,1 mil", "Fidelidade", "Enviar lookbook"],
        ["Camila Rocha", "85 99718-1102", "8 dias", "R$ 980", "Aniversario", "Cupom presente"],
        ["Juliana Alves", "85 98944-2210", "16 dias", "R$ 1,6 mil", "Em risco", "WhatsApp"],
        ["Rafaela Nunes", "85 99200-8139", "21 dias", "R$ 760", "Devolucoes", "Nota de ajuste"],
        ["Larissa Melo", "85 98763-9042", "31 dias", "R$ 3,4 mil", "VIP", "Novidade"],
        ["Fernanda Dias", "85 99620-4551", "45 dias", "R$ 540", "Inativa", "Reativar"],
        ["Patricia Souza", "85 99418-7006", "58 dias", "R$ 1,1 mil", "Fidelidade", "Alerta de pontos"],
      ],
    },
    bulkActions: {
      selected: "0 selecionados",
      hint: "Selecione clientes para enviar mensagens, atribuir tags ou exportar segmento.",
    },
    rail: {
      ...customersContent.rail,
      description: "VIP - WhatsApp opt-in",
      stats: [
        ["Vitalicio", "R$ 4,8 mil"],
        ["Pedidos", "23"],
        ["Ticket medio", "R$ 209"],
      ],
      loyalty: "R$ 182 em pontos disponiveis. Proximo nivel libera apos R$ 420 em compras.",
      actions: ["Reservar vestido midi preto", "Enviar cupom de aniversario", "Acompanhar ajuste"],
      purchases: [
        ["Vestido midi canelado", "Hoje - R$ 219"],
        ["Sandalia tiras nude", "18 mai - R$ 189"],
        ["Calca alfaiataria", "02 mai - R$ 249"],
      ],
    },
    detail: {
      ...customersContent.detail,
      breadcrumb: "Clientes / Mariana Costa",
      description: "Cliente VIP - Ultima compra ha 2 dias - WhatsApp opt-in",
      actions: ["Mensagem", "Editar perfil", "Novo pedido"],
      tags: ["VIP", "WhatsApp", "Sem debito"],
      stats: [
        ["Total gasto", "R$ 8.420"],
        ["Pedidos", "37"],
        ["Ticket medio", "R$ 227"],
        ["Pontos", "3.240"],
      ],
      tabs: ["Visao geral", "Pedidos", "Notas", "Preferencias"],
      recentOrders: [
        ["#1048", "2 dias atras", "R$ 420", "Pago"],
        ["#1032", "12 dias atras", "R$ 189", "Retirado"],
        ["#1017", "30 abr", "R$ 760", "Item devolvido"],
        ["#0991", "18 abr", "R$ 238", "Pago"],
      ],
      notes: [
        "Prefere vestidos de linho em cores neutras.",
        "Costuma comprar perto do dia de pagamento e responde no WhatsApp.",
        "Aniversario: 18 de agosto. Oferecer preview VIP antecipado.",
      ],
      loyaltyTier: {
        title: "Membro Gold",
        description: "R$ 580 ate o nivel Platinum",
      },
      nextActions: ["Enviar preview de aniversario", "Oferecer reposicao de linho", "Convidar para venda VIP"],
      timeline: [
        ["Comprou conjunto de linho", "2 dias atras"],
        ["Usou credito fidelidade", "12 dias atras"],
        ["Abriu campanha WhatsApp", "18 dias atras"],
        ["Devolveu blusa para troca de tamanho", "30 abr"],
      ],
    },
    labels: {
      loyaltyStatus: "Status de fidelidade",
      nextBestActions: "Proximas melhores acoes",
      recentPurchases: "Compras recentes",
      recentOrders: "Pedidos recentes",
      relationshipNotes: "Notas de relacionamento",
      viewAll: "Ver todos",
      loyaltyTier: "Nivel de fidelidade",
      timeline: "Timeline",
      promissory: "Promissoria",
    },
    promissory: {
      ...customersContent.promissory,
      labels: {
        creditPurchaseHistory: "Historico de compras a prazo",
        financialTimeline: "Timeline financeira",
        openInstallments: "Parcelas em aberto",
        pendingInstallments: "3 pendentes",
      },
    },
  },
  es: {
    ...customersContent,
    sidebar: {
      status: "2.418 clientes sincronizados",
      detailStatus: "Perfil de cliente abierto",
      promissoryStatus: "Promesa en analisis",
      operatorRole: "Mesa de clientes",
    },
    header: {
      title: "Clientes",
      description: "Sigue fidelidad, historial, cumpleanos, devoluciones y contactos.",
      searchPlaceholder: "Buscar nombre, telefono, CPF",
      campaignLabel: "Campana",
      actionLabel: "Agregar cliente",
    },
    metrics: [
      ["Clientes activos", "1.284", "Compraron en los ultimos 90 dias", "info"],
      ["Miembros fidelidad", "842", "R$ 38,2 mil en puntos", "success"],
      ["Cumpleanos de la semana", "19", "7 contactos de alto valor", "warning"],
      ["Tasa de recompra", "41%", "+5 pts vs mes pasado", "muted"],
    ],
    filters: [
      ["all", "Todos"],
      ["vip", "VIP"],
      ["birthday", "Cumpleanos"],
      ["at-risk", "En riesgo"],
      ["returns", "Devoluciones"],
      ["whatsapp", "WhatsApp opt-in"],
    ],
    table: {
      ...customersContent.table,
      title: "Lista de clientes",
      description: "Prioriza compradores por valor vitalicio, fidelidad y proxima accion.",
      segmentLabel: "Segmento",
      heads: ["Cliente", "Telefono", "Ultima compra", "Vitalicio", "Segmento", "Proxima accion"],
      rows: [
        ["Marina Costa", "85 99142-7712", "Hoy", "R$ 4,8 mil", "VIP", "Reservar vestido"],
        ["Beatriz Lima", "85 98801-3370", "2 dias", "R$ 2,1 mil", "Fidelidad", "Enviar lookbook"],
        ["Camila Rocha", "85 99718-1102", "8 dias", "R$ 980", "Cumpleanos", "Cupon regalo"],
        ["Juliana Alves", "85 98944-2210", "16 dias", "R$ 1,6 mil", "En riesgo", "WhatsApp"],
        ["Rafaela Nunes", "85 99200-8139", "21 dias", "R$ 760", "Devoluciones", "Nota de ajuste"],
        ["Larissa Melo", "85 98763-9042", "31 dias", "R$ 3,4 mil", "VIP", "Novedad"],
        ["Fernanda Dias", "85 99620-4551", "45 dias", "R$ 540", "Inactiva", "Reactivar"],
        ["Patricia Souza", "85 99418-7006", "58 dias", "R$ 1,1 mil", "Fidelidad", "Alerta de puntos"],
      ],
    },
    bulkActions: {
      selected: "0 seleccionados",
      hint: "Selecciona clientes para enviar mensajes, asignar tags o exportar segmento.",
    },
    rail: {
      ...customersContent.rail,
      description: "VIP - WhatsApp opt-in",
      stats: [
        ["Vitalicio", "R$ 4,8 mil"],
        ["Pedidos", "23"],
        ["Ticket medio", "R$ 209"],
      ],
      loyalty: "R$ 182 en puntos disponibles. Proximo nivel libera despues de R$ 420 en compras.",
      actions: ["Reservar vestido midi negro", "Enviar cupon de cumpleanos", "Acompanhar ajuste"],
      purchases: [
        ["Vestido midi acanalado", "Hoy - R$ 219"],
        ["Sandalia tiras nude", "18 may - R$ 189"],
        ["Pantalon sastrero", "02 may - R$ 249"],
      ],
    },
    detail: {
      ...customersContent.detail,
      breadcrumb: "Clientes / Mariana Costa",
      description: "Cliente VIP - Ultima compra hace 2 dias - WhatsApp opt-in",
      actions: ["Mensaje", "Editar perfil", "Nuevo pedido"],
      tags: ["VIP", "WhatsApp", "Sin deuda"],
      stats: [
        ["Total gastado", "R$ 8.420"],
        ["Pedidos", "37"],
        ["Ticket medio", "R$ 227"],
        ["Puntos", "3.240"],
      ],
      tabs: ["Resumen", "Pedidos", "Notas", "Preferencias"],
      recentOrders: [
        ["#1048", "Hace 2 dias", "R$ 420", "Pagado"],
        ["#1032", "Hace 12 dias", "R$ 189", "Retirado"],
        ["#1017", "30 abr", "R$ 760", "Item devuelto"],
        ["#0991", "18 abr", "R$ 238", "Pagado"],
      ],
      notes: [
        "Prefiere vestidos de lino en colores neutros.",
        "Suele comprar cerca del dia de pago y responde en WhatsApp.",
        "Cumpleanos: 18 de agosto. Ofrecer preview VIP anticipado.",
      ],
      loyaltyTier: {
        title: "Miembro Gold",
        description: "R$ 580 hasta el nivel Platinum",
      },
      nextActions: ["Enviar preview de cumpleanos", "Ofrecer reposicion de lino", "Invitar a venta VIP"],
      timeline: [
        ["Compro conjunto de lino", "Hace 2 dias"],
        ["Uso credito de fidelidad", "Hace 12 dias"],
        ["Abrio campana WhatsApp", "Hace 18 dias"],
        ["Devolvio blusa por cambio de talla", "30 abr"],
      ],
    },
    labels: {
      loyaltyStatus: "Estado de fidelidad",
      nextBestActions: "Proximas mejores acciones",
      recentPurchases: "Compras recientes",
      recentOrders: "Pedidos recientes",
      relationshipNotes: "Notas de relacion",
      viewAll: "Ver todos",
      loyaltyTier: "Nivel de fidelidad",
      timeline: "Timeline",
      promissory: "Promesa",
    },
    promissory: {
      ...customersContent.promissory,
      breadcrumb: "Clientes / Mariana Costa / Promesa",
      title: "Promesa de Mariana Costa",
      description:
        "Sigue cuotas, atrasos, pagos recientes, acuerdos e historial de compras a credito.",
      actions: ["Registrar pago", "Renegociar", "Exportar"],
      alertTitle: "Pago atrasado hace 12 dias",
      alertDescription:
        "La cuota vencida el 14 de mayo de 2026 aun no fue liquidada. Proxima accion recomendada: contacto por WhatsApp hoy.",
      metrics: [
        ["Valor abierto", "R$ 1.248,00", "3 cuotas pendientes"],
        ["Atrasado", "R$ 416,00", "12 dias vencidos"],
        ["Ultimo pago", "02 mayo 2026", "R$ 416 via Pix"],
        ["Limite a credito", "R$ 2.000,00", "62% utilizado"],
      ],
      installments: [
        ["14 mayo 2026", "Vencida hace 12 dias", "R$ 416,00", "Atrasada"],
        ["14 junio 2026", "Vence en 19 dias", "R$ 416,00", "Abierta"],
        ["14 julio 2026", "Vence en 49 dias", "R$ 416,00", "Abierta"],
      ],
      purchases: [
        ["#1048 - Vestido lino + sandalia", "02 mayo 2026", "R$ 1.248,00"],
        ["#0991 - Blusa sastrera", "18 abr 2026", "R$ 238,00"],
      ],
      timeline: [
        ["Pago recibido", "02 mayo - R$ 416 via Pix"],
        ["Compra en cuotas creada", "02 mayo - 3x de R$ 416"],
        ["Recordatorio enviado", "15 mayo - WhatsApp entregado"],
        ["Cuota atrasada", "26 mayo - 12 dias vencidos"],
      ],
      risk: {
        label: "Riesgo de cobranza",
        value: "Medio",
        description: "Cliente historicamente paga despues del primer recordatorio.",
      },
      labels: {
        creditPurchaseHistory: "Historial de compras a credito",
        financialTimeline: "Timeline financiera",
        openInstallments: "Cuotas abiertas",
        pendingInstallments: "3 pendientes",
      },
    },
  },
} as const;

export type CustomersContent = typeof customersContent;
