export {
  ChartBar as ChartIcon,
  Check as CheckIcon,
  Clock as ClockIcon,
  Briefcase as BriefcaseIcon,
  CalendarBlank as CalendarIcon,
  EnvelopeSimple as MailIcon,
  GearSix as GearIcon,
  Info as InfoIcon,
  List as MenuIcon,
  MagnifyingGlass as SearchIcon,
  Package as BoxIcon,
  Plus as PlusIcon,
  ShieldCheck as ShieldCheckIcon,
  Sparkle as SparkIcon,
  Users as UsersIcon,
} from "@phosphor-icons/react";
